#!/bin/bash

DMENU='rofi -width 45 -dmenu -i -l 7 -p Mocp:'
choice=$(echo -e "Open\nPlay/Pause\nNext\nPrevious\nShuffle\nRepeat\nExit" | $DMENU)

# check mocp is running
rez=$(mocp -i | wc -l)
if [ $rez -lt 1 ] ; then
  mocp -S 
fi

# make action
if [ "$choice" == 'Play/Pause' ]; then
  if [ $rez -lt 2 ] ; then
      echo P
    mocp -p 
  else 
      echo G
    mocp -G 
  fi
fi

case "$choice" in
  Next) mocp -f ;;
  Previous) mocp -r ;;
  Open) st -e "mocp" ;;
  Shuffle) mocp -t shuffle ;;
  Repeat) mocp -t repeat ;;
  Exit) mocp -x ;;
esac
